services:
  backend1:
    image: ronssm/copirinhago:latest
    pull_policy: always
    environment:
      - REDIS_CONN=redis:6379
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"
  backend2:
    image: ronssm/copirinhago:latest
    pull_policy: always
    environment:
      - REDIS_CONN=redis:6379
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"
  haproxy:
    image: haproxy:2.8-alpine
    pull_policy: always
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"
  redis:
    image: redis:7-alpine
    pull_policy: always
    ports:
      - "6379:6379"
    networks:
      - backend
    command: redis-server --maxmemory 120mb --maxmemory-policy allkeys-lru --tcp-keepalive 30 --timeout 0 --save "" --appendonly no --tcp-backlog 511
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 3s
    deploy:
      resources:
        limits:
          memory: 140M
          cpus: '0.4'
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
