services:
  rinhadebackend-aot:
    &api
    hostname: api01
    image: vyctor17/rinhadebackendaot:2025
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    build:
      context: .
      dockerfile: RinhaDeBackEnd-AOT/Dockerfile
    healthcheck:
      test: curl --silent --fail http://localhost:8080/payments-summary || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - ConnectionStrings__Redis=redis:6379
      - Gateways__Primary=http://payment-processor-default:8080
      - Gateways__Fallback=http://payment-processor-fallback:8080
      - DB_HOSTNAME=Host=db;Database=rinha;Username=admin;Password=123;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=10
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "110MB"

  rinhadebackend-aot02:
    <<: *api 
    hostname: api02
    depends_on:
      rinhadebackend-aot:
        condition: service_healthy

  nginx:
    image: nginx:latest
    networks:
      - backend
      - payment-processor
    volumes:
     - ./nginx-conf/default.conf:/etc/nginx/nginx.conf
    depends_on:
      rinhadebackend-aot:
        condition: service_healthy
      rinhadebackend-aot02:
        condition: service_healthy
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./pg-conf/script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "85MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
