services:
  cache:
    image: redis:7.2-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/lua:/etc/redis/lua:ro
    networks:
      - rinha-net
      - payment-processor
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "60MB"

  api01: &api01
    image: hramos13/rinha-backend-2025-node
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    depends_on:
      cache:
        condition: service_healthy
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  api02:
    <<: *api01
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  worker-job:
    image: hramos13/rinha-backend-2025-worker
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    depends_on:
      - cache
      - api01
      - api02
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "165MB"

  lb:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "45MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
