services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    depends_on:
      - app1
      - app2
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "30MB"

  app1:
    image: nathanfabio/rinha2025-golang:v1
    depends_on:
      - redis
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis:6379
      - APP_PORT=7070
      - MAX_WORKERS=2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "70MB"

  app2:
    image: nathanfabio/rinha2025-golang:v1
    depends_on:
      - redis
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis:6379
      - APP_PORT=7070
      - MAX_WORKERS=2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "70MB"

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no --maxmemory 32mb --maxmemory-policy allkeys-lru
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "180MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true