x-app-base: &app-base
  image: wlagent/wza-go:latest
  environment:
    - DEFAULT_URL=http://payment-processor-default:8080
    - FALLBACK_URL=http://payment-processor-fallback:8080
    - MAX_WORKERS=2
    - MAX_ACK_PENDING=100
    - BROKER_URL=nats://nats:4222
  networks:
    - backend
    - payment-processor
  volumes:
    - rinha-store:/data
  deploy:
    resources:
      limits:
        cpus: "0.55"
        memory: "120MB"

services:
  nats:
    image: nats:2.10-alpine
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - backend
    volumes:
      - nats-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "25MB"

  app1:
    <<: *app-base
    depends_on:
      - nats

  app2:
    <<: *app-base
    depends_on:
      - nats

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "85MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  rinha-store:
  nats-data:
