##############################################################################

x-backend-templates:
  app: &app
    image: csouzadocker/rinha-2025-postgres-native:latest
    depends_on:
      backend-db:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"

  app-env: &app-env
    ACTIVE_MONITOR: "true"
    SERVER_PORT: "8080"
    VIRTUAL_THREADS: "true"
    THREAD_POOL_SIZE: "10"
    QUEUE_SIZE: "500"
    QUEUE_IS_FAIR: "true"
    WEBCLIENT_MAX_CONNECTION: "200"
    PAYMENT_PROCESSOR_MAX_RETRIES: "5"
    PAYMENT_PROCESSOR_REQUEST_TIMEOUT: "10000"
    PAYMENT_PROCESSOR_WORKERS: "1"
    payment-processor.default.url: "http://payment-processor-default:8080"
    payment-processor.fallback.url: "http://payment-processor-fallback:8080"
    SPRING_APPLICATION_JSON: >
      {
        "server.port":8080,
        "spring.application.name": "ccs1201-rinha-backend-2025",
        "spring.threads.virtual.enabled": false,
        "server.servlet.session.persistent": false,
        "server.servlet.session.timeout": 0,
        "spring.main.banner-mode": "off",
        "spring.jmx.enabled": false,
        "spring.application.admin.enabled": false,
        "spring.mvc.async.request-timeout": -1,
        "spring.mvc.dispatch-options-request": false,
        "spring.mvc.dispatch-trace-request": false,
        "spring.mvc.log-request-details": false,
        "server.undertow.threads.io": 2,
        "server.undertow.threads.worker": 8,
        "server.undertow.buffer-size": 1024,
        "server.undertow.direct-buffers": true,
        "server.undertow.max-http-post-size": "1KB",
        "server.undertow.no-request-timeout": 2000,
        "spring.datasource.url": "jdbc:postgresql://postgres:5432/rinha",
        "spring.datasource.username": "rinha",
        "spring.datasource.password": "rinha",
        "spring.datasource.hikari.maximum-pool-size": 3,
        "spring.datasource.hikari.minimum-idle": 3,
        "spring.datasource.hikari.connection-timeout": 2000,
        "spring.datasource.hikari.idle-timeout": 300000,
        "spring.datasource.hikari.max-lifetime": 600000,
        "spring.datasource.hikari.connection-init-sql": "SELECT 1 WHERE 1 = 1;",
        "payment-processor.default.url": "http://payment-processor-default:8080",
        "payment-processor.fallback.url": "http://payment-processor-fallback:8080",
        "spring.mvc.log-resolved-exception": false,
        "logging.level.root": "error",
        "logging.level.br.com.ccs.rinha": "info"
      }

#####################################################################################

services:
  backend-db:
    image: postgres:17-alpine
    container_name: backend-db
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./init.sql/init-backend-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sql/init-config.sh:/docker-entrypoint-initdb.d/init-config.sh
    #      - backend-db:/var/lib/postgresql
    ports:
      - "54323:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha" ]
      interval: 3s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "125MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    environment:
      <<: *app-env

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    environment:
      <<: *app-env

  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
