x-service-templates:
  go-backend: &go-backend
    image: davidalecrim1/rinha-with-go-2025:v2.0.1-api
    networks:
      - app
      - payment-processor
    depends_on:
      - redis
    volumes:
      - api-sockets:/var/run:rw

services:
  go-backend-1:
    <<: *go-backend
    container_name: go-backend-1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - ENABLE_PROFILING=false
      - REDIS_ADDR=/var/run/redis.sock
      - UNIX_SOCKET=/var/run/api_1.sock
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
  go-backend-2:
    <<: *go-backend
    container_name: go-backend-2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - ENABLE_PROFILING=false
      - REDIS_ADDR=/var/run/redis.sock
      - UNIX_SOCKET=/var/run/api_2.sock
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  go-worker-1:
    image: davidalecrim1/rinha-with-go-2025:v2.0.1-worker
    container_name: go-worker-1
    networks:
      - payment-processor
    depends_on:
      - redis
      - go-backend-1
      - go-backend-2
    volumes:
      - api-sockets:/var/run:rw
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - MONITOR_HEALTH=true
      - ENABLE_PROFILING=false
      - REDIS_ADDR=/var/run/redis.sock
      - WORKERS=25
      - LENGTH_PROCESSOR_BUFFER=10000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  redis:
    image: redis:8.0
    container_name: redis-db
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
      - api-sockets:/var/run:rw
    command: bash -c "rm -rf /var/run/redis.sock && redis-server /usr/local/etc/redis.conf"
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  load-balancer:
    container_name: load-balancer-nginx
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - api-sockets:/var/run:rw
    depends_on:
      - go-backend-1
      - go-backend-2
    ports:
      - "9999:80"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true

volumes:
  api-sockets:
