x-service-templates:
  backend: &backend
    image: geazianc/rinha25:v3
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "160MB"
    depends_on:
      - valkey-server
    networks:
      - backend
      - payment-processor

services:
  api1:
    <<: *backend
    ports:
      - 8081:8080

  api2:
    <<: *backend
    ports:
      - 8082:8080

  valkey-server:
    image: valkey/valkey:8.1.3-alpine
    container_name: valkey-server
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "15MB"
    networks:
      - backend


  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "15MB"
    depends_on:
      - api1
      - api2
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
