version: '3.8'

x-services-templates:
  backend-app: &backend-app
    image: docker.io/jairoandre/rb2025-kotlin:v1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "165MB"

services:
  # Load Balancer / API Gateway
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  # Backend Instance 1
  backend1:
    <<: *backend-app
    container_name: backend1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - OTHER_BACKEND_URL=http://backend2:9999
      - STANDALONE=false
      - CHECK_HEALTH=true
      - DEFAULT_TOLERANCE=2000
      - NUM_WORKERS=60
      - MAX_CONCURRENCY=30
      - WORKER_HEALTH_INTERVAL=100
      - WORKER_RESEND_INTERVAL=100
  # Backend Instance 2
  backend2:
    <<: *backend-app
    container_name: backend2
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - OTHER_BACKEND_URL=http://backend1:9999
      - STANDALONE=false
      - CHECK_HEALTH=false
      - DEFAULT_TOLERANCE=2000
      - NUM_WORKERS=60
      - MAX_CONCURRENCY=30
      - WORKER_HEALTH_INTERVAL=100
      - WORKER_RESEND_INTERVAL=100

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

