services:
  lb:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 30M
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app-1
      - app-2

  app-1:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 30M
    image: daviddeltasierra/rinha-2025-go
    restart: always
    environment:
      - MASTER=true
    depends_on:
      postgres:
        condition: service_healthy

  app-2:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 30M
    image: daviddeltasierra/rinha-2025-go
    restart: always
    environment:
      - MASTER=false
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 260M
    image: postgres:alpine
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 6
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true