services:
  lb:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 60M
    image: daviddeltasierra/rinha-2025-go-2:1.9
    volumes:
      - /tmp:/tmp
    environment:
      - GATEWAY=true
    depends_on:
      - app-1
      - app-2
    ports:
      - "9999:8080"

  app-1:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 70M
    image: daviddeltasierra/rinha-2025-go-2:1.9
    volumes:
      - /tmp/app1:/tmp/app1
    environment:
      - GATEWAY=false
      - SOCK=/tmp/app1/unix.sock
    depends_on:
      - postgres

  app-2:
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 70M
    image: daviddeltasierra/rinha-2025-go-2:1.9
    volumes:
      - /tmp/app2:/tmp/app2
    environment:
      - GATEWAY=false
      - SOCK=/tmp/app2/unix.sock
    depends_on:
      - postgres

  postgres:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 150M
    image: postgres:alpine
    user: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true