services:
  lb:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - socket-volume:/socket
    ports:
      - "9999:9999"
    depends_on:
      - app-1
      - app-2

  app-1: &app-base
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: 50M
    image: daviddeltasierra/rinha-2025-go
    volumes:
      - socket-volume:/socket
    restart: always
    environment:
      - SOCKET_PATH=/socket/app1.sock
    depends_on:
      postgres:
        condition: service_healthy

  app-2:
    <<: *app-base
    environment:
      - SOCKET_PATH=/socket/app2.sock

  postgres:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
    image: postgres:alpine
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 6
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha

volumes:
  socket-volume:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true