services:
  nginx:
    image: nginx:1.29-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - srv1
      - srv2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "35MB"

  srv1:
    image: alvesluc/rinha-2025-node:latest
    build: .
    platform: linux/amd64
    networks:
      - backend
      - payment-processor
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "105MB"

  srv2:
    image: alvesluc/rinha-2025-node:latest
    build: .
    platform: linux/amd64
    networks:
      - backend
      - payment-processor
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "105MB"

  redis:
    image: redis:8.0.3-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "105MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true