name : payment-proxy

networks:
  acsbackend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
  payment-processor:
    external: true

x-service-templates:
  base: &apibase
    image: acslook/payment-proxy:v6

services:  
  network-setup:
    image: docker:latest
    container_name: network-setup
    command: >
      sh -c "docker network inspect payment-proxy_acsbackend || docker network create --driver bridge --subnet 172.25.0.0/16 payment-proxy_acsbackend"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
  api1:
      <<: *apibase
      container_name: api1
      environment:
        - CONN_STRING=postgres://rinha25:rinha25@db:5432/payments_db?sslmode=disable
        - REDIS_URL=redis:6379
        - GATEWAY_DEFAULT_URL=http://payment-processor-default:8080
        - GATEWAY_FALLBACK_URL=http://payment-processor-fallback:8080
      networks:
        acsbackend:
          ipv4_address: 172.25.0.10
        payment-processor: {}
      restart: unless-stopped
      command: ["server"]
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: "30MB"
      depends_on:
        - network-setup
  api2:
    <<: *apibase
    container_name: api2
    environment:
      - CONN_STRING=postgres://rinha25:rinha25@db:5432/payments_db?sslmode=disable
      - REDIS_URL=redis:6379
      - GATEWAY_DEFAULT_URL=http://payment-processor-default:8080
      - GATEWAY_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      acsbackend:
        ipv4_address: 172.25.0.11
      payment-processor: {}
    restart: unless-stopped
    command: ["server"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "30MB"
    depends_on:
      - network-setup

  worker:
      <<: *apibase
      container_name: worker
      environment:
        - CONN_STRING=postgres://rinha25:rinha25@db:5432/payments_db?sslmode=disable
        - REDIS_URL=redis:6379
        - GATEWAY_DEFAULT_URL=http://payment-processor-default:8080
        - GATEWAY_FALLBACK_URL=http://payment-processor-fallback:8080
      networks:
        acsbackend:
          ipv4_address: 172.25.0.12
        payment-processor: {}
      restart: unless-stopped
      command: ["worker"]
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: "200MB"
      depends_on:
        - network-setup
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
      - worker
      - network-setup
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "80MB"
    networks:
      acsbackend:
        ipv4_address: 172.25.0.13
