services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - api-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "38MB"

  db:
    image: postgres:17-alpine
    hostname: rinha-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "120MB"

  api1: &api
    image: ghcr.io/mpedroni/rinha-de-backend-2025:v1.0.0
    hostname: api1
    environment:
      - SERVICE_NAME=api-1
      - PORT=3000
      - LOG_LEVEL=none
      - DB_CONNECTION_STRING=postgres://postgres:postgres@rinha-db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKERS_COUNT=4
    networks:
      - api-network
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "96MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - SERVICE_NAME=api-2
      - PORT=3000
      - LOG_LEVEL=none
      - DB_CONNECTION_STRING=postgres://postgres:postgres@rinha-db:5432/rinha?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKERS_COUNT=4

networks:
  api-network:
    driver: bridge
  payment-processor:
    external: true
