version: '3.8'

services:
  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "15MB"

  api-1: &api
    image: jvradev/rinha-backend-payments:latest
    hostname: api-1
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_ADDRESS=redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "60MB"

  api-2:
    <<: *api
    hostname: api-2
    
  redis:
    image: redis:7-alpine
    container_name: redis-cache-rinha
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "275MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true