services:
  cache:
    image: redis:7.4.5-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: "25MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend-network
  
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "130MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend-network
  
  backend-01: &backend
    image: rafaelgiori/rinha-dotnet:amd64-1.0.2
    environment:
      MONITORED_PROCESSOR: "default"
      Cache__ConnectionString: "cache:6379"
      Database__ConnectionString: "Host=db;Database=rinha;Username=postgres;Password=postgres"
      PaymentProcessor__DefaultBaseUrl: "http://payment-processor-default:8080"
      PaymentProcessor__FallbackBaseUrl: "http://payment-processor-fallback:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "85MB"
    networks:
      - backend-network
      - payment-processor
  
  backend-02:
    <<: *backend
    environment:
      MONITORED_PROCESSOR: "fallback"
      Cache__ConnectionString: "cache:6379"
      Database__ConnectionString: "Host=db;Database=rinha;Username=postgres;Password=postgres"
      PaymentProcessor__DefaultBaseUrl: "http://payment-processor-default:8080"
      PaymentProcessor__FallbackBaseUrl: "http://payment-processor-fallback:8080"
  
  lb:
    image: nginx:1.29.0-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
      - backend-02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  payment-processor:
    external: true