services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    hostname: nginx-lb
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

  backend-1: &backend-template
    image: rodrigomilitao/rinha-go:2025
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - APP_INSTANCE_ID=app1
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '80MB'

  backend-2:
    <<: *backend-template
    environment:
      - APP_INSTANCE_ID=app2

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes: {}