services:
  db:
    container_name: db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./config/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130MB"
  
  payment-processor-mid-1: &api
    container_name: payment-processor-mid-1
    hostname: payment-processor-mid-1
    image: ferhgm/api-rinha-3:1
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '100MB'
  
  payment-processor-mid-2:
    <<: *api 
    container_name: payment-processor-mid-2
    hostname: payment-processor-mid-2
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-processor-mid-1
      - payment-processor-mid-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'
  
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true


