x-service-templates:
  backend: &backend
    image: guilhermesouzaaraujo/rinha-2025-node:latest
    depends_on:
      - redis
    networks:
      - payment-processor
      - backend
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://localhost:8001
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://localhost:8002
    restart: unless-stopped

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "12MB"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: >
      redis-server
      --maxmemory 40mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 0
      --tcp-backlog 511

  backend-01:
    <<: *backend
    container_name: backend-01
    hostname: backend-01
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "164MB"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=01
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://localhost:8001
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://localhost:8002

  backend-02:
    <<: *backend
    container_name: backend-02
    hostname: backend-02
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "166MB"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=02
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://localhost:8001
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://localhost:8002

  nginx:
    image: nginx:alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
      - backend-02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "8MB"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  redis_data:
    driver: local
