x-service-templates:
  api: &api
    image: flads/rinha25-go-api:0.1.0
    user: "1000:1001"
    networks:
      - main-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "55MB"

  worker: &worker
    image: flads/rinha25-go-worker:0.0.2
    container_name: worker
    networks:
      - main-network
      - payment-processor
    depends_on:
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "80MB"

services:
  api-1:
    <<: *api
    container_name: api-1
    volumes:
      - sockets:/tmp/sockets
    environment:
      - SOCKET_PATH=/tmp/sockets/api-1.sock

  api-2:
    <<: *api
    container_name: api-2
    volumes:
      - sockets:/tmp/sockets
    environment:
      - SOCKET_PATH=/tmp/sockets/api-2.sock

  worker-1:
    <<: *worker
    container_name: worker-1

  worker-2:
    <<: *worker
    container_name: worker-2

  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    user: "1000:1001"
    ports:
      - "9999:9999"
    networks:
      - main-network
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - main-network
    command: ["redis-server"]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

volumes:
  sockets:

networks:
  main-network:
    driver: bridge
  payment-processor:
    external: true