services:
  haproxy:
    image: haproxy:3.2.3-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets:rw
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
    networks:
      - backend
    ports:
      - 9999:80
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
      - rinha-gateway-3

  rinha-gateway-1:
    image: ghcr.io/alan-venv/rinha-gateway:6.3
    container_name: rinha-gateway-1
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.1
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  rinha-gateway-2:
    image: ghcr.io/alan-venv/rinha-gateway:6.3
    container_name: rinha-gateway-2
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.2
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  rinha-gateway-3:
    image: ghcr.io/alan-venv/rinha-gateway:6.3
    container_name: rinha-gateway-3
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.3
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  rinha-db:
    image: ghcr.io/alan-venv/rinha-database:6.3
    container_name: rinha-db
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  sockets:

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
