services:
  load-balancer:
    image: nginx:latest
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "42MB"
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    networks:
      - backend
      - payment-processor

  backend-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: boscobecker/dotnet-rinha:latest
    container_name: backend-1
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_CONNECTION=redis:6379,abortConnect=false
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor

  backend-2:
    image: boscobecker/dotnet-rinha:latest
    container_name: backend-2
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_CONNECTION=redis:6379,abortConnect=false
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor

  redis:
    image: redis:7.2-alpine
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
