x-service-templates:
  api: &api
    image: ghcr.io/railson-ferreira/rinha-de-backend-2025-dart:latest
    environment:
      - REPOSITORY_URL=ws://repository:8080
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      - repository
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "100MB"

services:
  repository:
    image: ghcr.io/railson-ferreira/rinha-de-backend-2025-dart/repository:latest
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: "100MB"

  api1:
    <<: *api
  api2:
    <<: *api

  pingora:
    image: ghcr.io/railson-ferreira/rinha-de-backend-2025-dart/pingora:latest
    ports:
      - "9999:8080"
    environment:
        - HOSTS=api1:8080,api2:8080
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true