services:
  backend:
    image: felipeschirmann/rinha-backend-2025:13.1.0
#    image: rinha-backend:latest
    container_name: felipeschirmann-rinha
    environment:
      # --- Performance Tuning: Reduced queue sizes to match limited CPU resources ---
      # This prevents the application from accepting too many requests too quickly,
      # which leads to resource starvation and timeouts.
      APP_QUEUE_MAX_CAPACITY: "20000"
      APP_QUEUE_BASE_CAPACITY: "10000"

     # --- Client and Health Check Settings ---
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
      APP_HEALTHCHECK_FIXED_DELAY: "5s"
      APP_HEALTHCHECK_INITIAL_DELAY: "1s"
      APP_CLIENT_RESPONSE_TIMEOUT: "10s" # Slightly increased for more tolerance under load
      APP_CLIENT_CONNECT_TIMEOUT: "5s"
      APP_WORKER_LOG_HTTP_FAILURES: "false"
      APP_WORKER_LOG_NETWORK_FAILURES: "false"
      APP_WORKER_LOG_SUCCESSFUL_PAYMENTS: "false"
    sysctls:
      net.core.somaxconn: 4096
    ports:
      - "9999:8080"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus:  "1.5"
          memory: "350MB"

networks:
  payment-processor:
    # This assumes the network is created externally by the payment-processor's docker-compose.
    external: true
