services:
  haproxy:
    networks:
      - backend
    image: haproxy:3.2.3-alpine3.22
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"

  api1: &api
    image: gdx64/rinha2025:latest
    hostname: api1
    environment:
      - DEFAULT_PAYMENT=http://payment-processor-default:8080
      - FALLBACK_PAYMENT=http://payment-processor-fallback:8080
      - DB_URL=http://db-api:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "50MB"
  api2:
    <<: *api
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "50MB"
  db-api:
    <<: *api
    hostname: db-api
    environment:
      - IS_DB_SERVICE=true
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true