x-api-template: &api-template
    image: pauloricardo45657/rinha-2025-api:v1.5
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "140MB"

services:
  api1:
    <<: *api-template
    container_name: api1
    depends_on:
      - health
      - redis

  api2:
    <<: *api-template
    container_name: api2
    depends_on:
      - health
      - redis

  health:
    image: pauloricardo45657/rinha-2025-health:v1.0
    container_name: health
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

  redis:
    image: redis:7-alpine
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro1
    ports:
      - "9999:80"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

