x-service-templates:
  base: &base
    image: josiney/rdb25_02-amd64:e3188b24
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy

services:
  api1:
    <<: *base
    container_name: api1
    hostname: api1
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - PORT=9997
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: ./api

  api2:
    <<: *base
    container_name: api2
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - PORT=9998
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: ./api

  worker1:
    <<: *base
    container_name: worker1
    hostname: worker1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: ./worker

  redis:
    image: redis/redis-stack:7.2.0-v18
    container_name: redis-db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 250ms
      timeout: 2s
      retries: 10
    command:
      - redis-server
      - --loadmodule /opt/redis-stack/lib/redistimeseries.so
      - --appendonly no
      - --maxmemory 50mb
      - --save ""
      - --protected-mode no
    networks:
      - backend
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  lb:
    image: haproxy:latest
    container_name: haproxy_lb
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true