x-service-templates:
  base: &base
    image: josiney/rdb25_02-amd64:ae8517f3
    volumes:
      - sockets:/sockets
    networks:
      - backend
      - payment-processor


services:
  api1:
    <<: *base
    container_name: api1
    hostname: api1
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - SOCKET_PATH=/sockets/api1.sock
      - WORKER_SOCKET_PATH=/sockets/worker_http.sock
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: sh -c "umask 0 && ./api"
    depends_on:
      - worker1

  api2:
    <<: *base
    container_name: api2
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - SOCKET_PATH=/sockets/api2.sock
      - WORKER_SOCKET_PATH=/sockets/worker_http.sock
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: sh -c "umask 0 && ./api"
    depends_on:
      - worker1

  api3:
    <<: *base
    container_name: api3
    hostname: api3
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - SOCKET_PATH=/sockets/api3.sock
      - WORKER_SOCKET_PATH=/sockets/worker_http.sock
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: sh -c "umask 0 && ./api"
    depends_on:
      - worker1

  api4:
    <<: *base
    container_name: api4
    hostname: api4
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - SOCKET_PATH=/sockets/api4.sock
      - WORKER_SOCKET_PATH=/sockets/worker_http.sock
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: sh -c "umask 0 && ./api"
    depends_on:
      - worker1
  
  api5:
    <<: *base
    container_name: api5
    hostname: api5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - SOCKET_PATH=/sockets/api5.sock
      - WORKER_SOCKET_PATH=/sockets/worker_http.sock
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: sh -c "umask 0 && ./api"
    depends_on:
      - worker1

  worker1:
    <<: *base
    container_name: worker1
    hostname: worker1
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "150MB"
    environment:
      - SOCKET_PATH=/sockets/worker_http.sock
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: sh -c "umask 0 && ./worker"

  lb:
    image: haproxy:latest
    container_name: haproxy_lb
    volumes:
      - sockets:/sockets
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
      - api3
      - api4
      - api5
    ports:
      - 9999:80
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

volumes:
  sockets:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
