x-service-templates:
  api: &api
    image: josiney/rdb25_02-arm64:latest
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "40MB"
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy

services:
  api1:
    <<: *api
    container_name: api1
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - PORT=9997
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health


  api2:
    <<: *api
    container_name: api2
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - PORT=9998
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health

  redis:
    image: redis/redis-stack:7.2.0-v18
    container_name: redis-db
    environment:
      - REDISTIMESERIES_ARGS=DUPLICATE_POLICY=SUM
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 250ms
      timeout: 2s
      retries: 10
    networks:
      - backend
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "220MB" 
  
  nginx:
    container_name: rinha-nginx
    image: nginx:1.27.1-alpine
    command: sh -c "sleep 5s && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend

    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true 
