services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  api1: &api
    image: felipeamorimw/rinha25:latest
    container_name: rinha-api1
    hostname: api1
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=warn
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "90MB"

  api2:
    <<: *api
    container_name: rinha-api2
    hostname: api2

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    container_name: rinha-redis
    hostname: redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
