version: '3.8'

services:
  api01:
    image: suntzu12/quarkus-payment-router:10.0.0
    container_name: api1
    hostname: api01
    ports:
      - "8081:8080"
    environment:
      PROCESS_THREAD_POOL: 20
      QUARKUS_REST_CLIENT_DEFAULT_API_URL: http://payment-processor-default:8080
      QUARKUS_REST_CLIENT_FALLBACK_API_URL: http://payment-processor-fallback:8080
      QUARKUS_REST_CLIENT_STORAGE_API_URL: http://api2:8080
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "125MB"
    networks:
      - payment-router
      - payment-processor

  api02:
    image: suntzu12/quarkus-payment-storage:1.0.0
    container_name: api2
    hostname: api02
    ports:
      - "8082:8080"
    environment:
      LISTEN: 8080
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "125MB"
    networks:
      - payment-router

  load_balancer:
    image: suntzu12/lua-nginx-loadbalancer:20250803010034
    container_name: load_balancer
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    networks:
      - payment-router

networks:
  payment-router:
    driver: bridge
  payment-processor:
    external: true