services:
  api1:
    image: brunosilvadev/rinha-2025:latest
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_CONNECTION_STRING=redis:6379
      - Logging__LogLevel__Default=Debug
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 125M

  api2:
    image: brunosilvadev/rinha-2025:latest
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_CONNECTION_STRING=redis:6379
      - Logging__LogLevel__Default=Debug
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 125M

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 32M

  redis:
    image: redis:7-alpine
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 68M

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
