services:
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    command: postgres -c max_connections=450 -c shared_buffers=40MB -c effective_cache_size=120MB -c work_mem=4MB -c maintenance_work_mem=16MB -c synchronous_commit=off -c fsync=off
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha"]
      interval: 2s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_load_balancer
    ports:
      - "9999:9999"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  api01: &api
    container_name: api01
    image: franklaercio/rinha-backend-2025:latest
    hostname: api01
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rinha
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      HTTP_PORT: "8080"
      PAYMENT_WORKERS: "12"
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50M"

  api02:
    <<: *api
    container_name: api02
    hostname: api02

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true