x-service-templates:
  go-backend: &go-backend
    image: davidalecrim1/rinha-with-go-2025:v1.1.0-redis-extreme-api
    networks:
      - app
      - payment-processor
    depends_on:
      - redis

services:
  go-backend-1:
    <<: *go-backend
    container_name: go-backend-1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=payment-processor-fallback:8080
      - PORT=80
      - REDIS_ADDR=redis-db:6379
      - ENABLE_PROFILING=false
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
  go-backend-2:
    <<: *go-backend
    container_name: go-backend-2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=payment-processor-fallback:8080
      - PORT=80
      - REDIS_ADDR=redis-db:6379
      - ENABLE_PROFILING=false
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  go-worker-1:
    image: davidalecrim1/rinha-with-go-2025:v1.1.0-redis-extreme-worker
    networks:
      - payment-processor
    depends_on:
      - redis
      - go-backend-1
      - go-backend-2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=payment-processor-fallback:8080
      - REDIS_ADDR=redis-db:6379
      - MONITOR_HEALTH=true
      - ENABLE_PROFILING=false
      - WORKERS=50
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  redis:
    image: redis:8.0-alpine
    container_name: redis-db
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - app
      - payment-processor
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  load-balancer:
    container_name: load-balancer-extreme-proxy
    image: davidalecrim1/extreme-proxy:v0.4.0
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - go-backend-1
      - go-backend-2
    ports:
      - "9999:9999"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
