networks:
    payment-processor:
        name: payment-processor
        driver: bridge
services:
    db:
        image: postgres:17-alpine
        hostname: db
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
        volumes:
            - ./pg.conf:/etc/postgresql.conf:ro
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - payment-processor
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: "150MB"
    locker:
        image: mxlange/locker:latest
        hostname: locker
        ports:
            - "8888:8080"
        networks:
            - payment-processor
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "30MB"
    api1: &api
        image: mxlange/rinha-go-faster:latest
        hostname: api1
        environment:
            - BASE_DEFAULT_URL=http://payment-processor-default:8080
            - BASE_FALLBACK_URL=http://payment-processor-fallback:8080
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
            - WORKER_CONCURRENCY=42
            - LOCKER_URL=locker:8080
        networks:
            - payment-processor
        depends_on:
            db:
                condition: service_healthy
            locker:
                condition: service_started
        deploy:
            resources:
                limits:
                    cpus: "0.40"
                    memory: "70MB"
    api2:
        <<: *api
        hostname: api2
    nginx:
        image: nginx:1.25-alpine
        container_name: rinha-nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2
        ports:
            - "9999:9999" # Só Nginx fica exposto
        networks:
            - payment-processor
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: "30MB"
