services:
  memdb:
    image: pedrohsbarbosa99/rinha-golang-2025:0.2.1
    command: ["./memdb"]
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 60M
    restart: unless-stopped

  app1:
    image: pedrohsbarbosa99/rinha-golang-2025:0.2.1
    command: ["./main"]
    environment:
      - MEMDB_SOCKET=/tmp/kvstore.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    depends_on:
      - memdb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 70M
    restart: unless-stopped

  app2:
    image: pedrohsbarbosa99/rinha-golang-2025:0.2.1
    command: ["./main"]
    environment:
      - MEMDB_SOCKET=/tmp/kvstore.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    depends_on:
      - memdb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 70M
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
    restart: unless-stopped

volumes:
  memsock:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

