x-service-templates:
  server: &server
    image: lucasgoveia/rinha-2025-api:ca8d8d87e0420f8
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '60M'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    networks:
      - backend
      - payment-processor
    restart: always
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '80M'

  server1:
    <<: *server
    container_name: server1
    hostname: server1
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7118
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/rinha2025?pool_max_conns=10&pool_min_conns=2&pool_max_conn_idle_time=30s&pool_max_conn_lifetime=5m&pool_health_check_period=30s
      - SERVICE_DEFAULT_URL=http://payment-processor-default:8080/payments
      - SERVICE_FALLBACK_URL=http://payment-processor-fallback:8080/payments
      - SERVICE_DEFAULT_HEALTH_URL=http://nginx:9000/default/payments/service-health
      - SERVICE_FALLBACK_HEALTH_URL=http://nginx:9000/fallback/payments/service-health


  server2:
    <<: *server
    container_name: server2
    hostname: server2
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7118
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/rinha2025?pool_max_conns=10&pool_min_conns=2&pool_max_conn_idle_time=30s&pool_max_conn_lifetime=5m&pool_health_check_period=30s
      - SERVICE_DEFAULT_URL=http://payment-processor-default:8080/payments
      - SERVICE_FALLBACK_URL=http://payment-processor-fallback:8080/payments
      - SERVICE_DEFAULT_HEALTH_URL=http://nginx:9000/default/payments/service-health
      - SERVICE_FALLBACK_HEALTH_URL=http://nginx:9000/fallback/payments/service-health

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '128M'

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true