x-build_template: &build
  image: niltonkummer/rinha-backend-2025:1.0.3
  networks:
    - backend-network
    - payment-processor

services:
  api1: &api
    <<: *build
    command: [ "/bin/api", "api" ]
    hostname: api1
    environment:
      - API_NAME=api1
    depends_on:
      - cache
    volumes:
      - unix-sock:/unix-sock:rw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "36MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - API_NAME=api2

  api3:
    <<: *api
    hostname: api3
    environment:
      - API_NAME=api3

  consumer1:
    <<: *build
    command: [ "/bin/api", "consumer" ]
    hostname: consumer1
    volumes:
      - unix-sock:/unix-sock:rw
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "40MB"

  cache:
    <<: *build
    command: [ "/bin/api", "cache" ]
    hostname: cache
    volumes:
      - unix-sock:/unix-sock:rw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "152MB"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - unix-sock:/unix-sock:rw
    depends_on:
      - api1
      - api2
      - api3
    ports:
      - "9999:9999"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

volumes:
  unix-sock:

networks:
  backend-network:
    driver: bridge
  payment-processor:
    external: true
