x-image: &image
  image: niltonkummer/rinha-backend-2025:1.0.2

services:
  api1: &api
    <<: *image
    command: [ "/bin/api", "api" ]
    hostname: api1
    networks:
      - backend
      - payment-processor
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  api2:
    <<: *api
    hostname: api2

  consumer1: &consumer1
    <<: *image
    command: [ "/bin/api", "consumer" ]
    hostname: consumer1
    networks:
      - backend
      - payment-processor
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  cache:
    <<: *image
    command: [ "/bin/api", "cache" ]
    hostname: cache
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
