name: DaniloSantanaRB2025

services:
  api-1: &api-service
    image: danilosantanaaa/rinha:2025
    expose:
      - "8080"
    ports:
      - "3001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostgreSQL=User Id=postgres;Password=password;Server=rinha-db;Port=5432;Database=rinha
      - PaymentProcessorDefault=http://payment-processor-default:8080
      - PaymentProcessorFallback=http://payment-processor-fallback:8080
    depends_on:
      - rinha-db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "85MB"
  api-2:
    <<: *api-service
    ports:
      - "3002:8080"

  load-balancer:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"

  rinha-db:
    image: postgres:17-alpine
    networks:
      - backend
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rinha" ]
      interval: 2s
      retries: 5
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    name: payment-processor
    driver: bridge
    external: true