services:
  api-1:
    image: gabxdevv/rinha-backend-2025-java-super-bolado:1.0.0
    container_name: gaxdev-backend-1
    environment:
      RETRY_API_DEFAULT: 5
      WORKER_POOL_SIZE: 21
      WORKERS_THREAD_POOL_SIZE: 10
      USER_SERVER: true
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      BACK_END_URL: http://backend-2:8080
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: api-2
      EXTERNAL_UDP_PORT: 9004

      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '175MB'

  api-2:
    image: gabxdevv/rinha-backend-2025-java-super-bolado:1.0.0
    container_name: gaxdev-backend-2
    restart: always
    environment:
      RETRY_API_DEFAULT: 5
      WORKER_POOL_SIZE: 21
      API_ROUTER_POOL_SIZE: 3
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      USER_SERVER: false
      BACK_END_URL: http://backend-1:8080
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: api-1
      EXTERNAL_UDP_PORT: 9003
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '175MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true