version: '3.8'

services:
  api1:
    image: steixeira93/rinha-2025-go:latest
    platform: linux/amd64
    command: ["./main", "api"]
    hostname: api1
    environment:
      HTTP_PORT: "8080"
      RPC_ADDR: "cache:9090"
      PROCESSOR_DEFAULT_URL: "http://processor-default:8080"
      PROCESSOR_FALLBACK_URL: "http://processor-fallback:8080"
    depends_on:
      - cache
    networks:
      - backend-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api2:
    image: steixeira93/rinha-2025-go:latest
    platform: linux/amd64
    command: ["./main", "api"]
    hostname: api2
    environment:
      HTTP_PORT: "8080"
      RPC_ADDR: "cache:9090"
      PROCESSOR_DEFAULT_URL: "http://processor-default:8080"
      PROCESSOR_FALLBACK_URL: "http://processor-fallback:8080"
    depends_on:
      - cache
    networks:
      - backend-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  consumer:
    image: steixeira93/rinha-2025-go:latest
    platform: linux/amd64
    command: ["./main", "consumer"]
    hostname: consumer
    environment:
      RPC_ADDR: "cache:9090"
      PROCESSOR_DEFAULT_URL: "http://processor-default:8080"
      PROCESSOR_FALLBACK_URL: "http://processor-fallback:8080"
      MAX_CONCURRENT_JOBS: "100"
      BATCH_SIZE: "50"
      PROCESSING_TIMEOUT: "30s"
      HEALTH_CHECK_INTERVAL: "5s"
      CIRCUIT_BREAKER_THRESHOLD: "10"
    depends_on:
      - cache
    networks:
      - backend-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  cache:
    image: steixeira93/rinha-2025-go:latest
    platform: linux/amd64
    command: ["./main", "cache"]
    hostname: cache
    environment:
      RPC_ADDR: ":9090"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "70MB"

networks:
  backend-network:
    driver: bridge
  payment-processor:
    external: true
