services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    deploy: 
      resources:
        limits:
          cpus: '0.15'
          memory: '30MB'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  api01: &api01
    image: antoniocarvalhodev/rinha:1.0
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    deploy: 
      resources:
        limits:
          cpus: '0.6'
          memory: '150MB'
  api02: 
    <<: *api01
    
  lb:
    image: nginx:1.27-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - api01
      - api02
    deploy: 
      resources:
        limits:
          cpus: '0.15'
          memory: '20MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true