services:
  nginx:
    image: nginx:1.25-alpine
    container_name: my-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
  api1: &api
    image: enermaxx/rinha-backend:1.0.0
    container_name: springboot-api1
    hostname: api1
    ports:
      - "7777:8080"
    environment:
      - HOST_TO_LOCK=api2
      - PORT_TO_LOCK=8080
      - MAIN_PROCESSOR_HOST=payment-processor-default
      - MAIN_PROCESSOR_PORT=8080
      - FALLBACK_PROCESSOR_HOST=payment-processor-fallback
      - FALLBACK_PROCESSOR_PORT=8080
      - INSTANCE_ID=API-1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "150MB"

  api2:
    <<: *api
    container_name: springboot-api2
    hostname: api2
    ports:
      - "7778:8080"
    environment:
      - HOST_TO_LOCK=api1
      - PORT_TO_LOCK=8080
      - MAIN_PROCESSOR_HOST=payment-processor-default
      - MAIN_PROCESSOR_PORT=8080
      - FALLBACK_PROCESSOR_HOST=payment-processor-fallback
      - FALLBACK_PROCESSOR_PORT=8080
      - INSTANCE_ID=API-2
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "150MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true