services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api1
      - api2
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api1: &api
    image: thomazmbonfim/rinha-de-backend-2025:latest
    hostname: api1
    environment:
      - REDIS_URL=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  api2: 
    <<: *api
    hostname: api2
    environment:
      - REDIS_URL=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  redis:
    image: redis:7.2-alpine 
    container_name: redis-rinha
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
networks:
    backend:
      driver: bridge
    payment-processor: 
      name: payment-processor
      external: true
