x-web-template: &web-template
  image: davi64lima/rinha-backend
  environment:
    DEFAULT_PROCESSOR_URL: 'http://payment-processor-default:8080'
    FALLBACK_PROCESSOR_URL: 'http://payment-processor-fallback:8080'
    REDIS_URL: redis://cache:6379
  depends_on:
    - cache
  networks:
    - payment-processor
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: "0.55"
        memory: "90MB"

services:
  web1:
    <<: *web-template
    ports:
      - "3001:3000"

  web2:
    <<: *web-template
    ports:
      - "3002:3000"

  cache:
    image: redis:7.2-alpine
    command: ["redis-server", "--dbfilename", "none"]
    ports:
      - "6379:6379"
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "70MB"

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - web1
      - web2
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  payment-processor:
    external: true
