version: "3.8"

services:
  api01: &api
    image: danielwisky/rinha-java-2025:1.0.2
    hostname: api01
    environment:
      - POSTGRES_URI=jdbc:postgresql://db:5432/rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "110MB"
    networks:
      - backend
      - payment-processor

  api02:
    <<: *api
    hostname: api02
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "110MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - backend

  db:
    image: postgres:15-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rinha -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true