services:
  rinha:
    image: "joaoprocopio/rinha:amd64-20250729022334"
    platform: "linux/amd64"
    networks:
      - "payment-processor"
    environment:
      RINHA_HOST: "0.0.0.0"
      RINHA_PORT: "9999"
      RINHA_DEFAULT_BACKEND_ADDR: "127.0.0.1:8001"
      RINHA_FALLBACK_BACKEND_ADDR: "127.0.0.1:8002"
    ports:
      - target: "9999"
        published: "9999"
        protocol: "tcp"
        mode: "host"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
        reservations:
          cpus: "1.5"
          memory: "350MB"

networks:
  payment-processor:
    external: true
