version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 60MB
  
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 160MB

  backend1: &backend
    image: andersonhqds/nestjs-rinha-be-2025:1.0.7
    container_name: backend1
    hostname: backend1
    platform: linux/amd64
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 60MB

  backend2:
    <<: *backend
    container_name: backend2
    hostname: backend2
    ports:
      - 3001:3000

  nginx:
    image: nginx:latest
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 10MB

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
  