x-service-templates:
  api: &api
    image: wellingtonbp/rinha_pure_ex:ets
    pull_policy: always
    networks:
      - payment-processor
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '160MB'

  server: &server
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-backend-ex
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

services:
  api1:
    <<: *api
    container_name: api-1
    hostname: api-1
    environment:
      PAYMENT_SERVICE_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_SERVICE_URL_FALLBACK: http://payment-processor-fallback:8080
      WORKERS_COUNT: 6
      RELEASE_COOKIE: rinha
      RELEASE_NODE: api@api1
      RELEASE_DISTRIBUTION: sname
      SIBLING: api@api2

  api2:
    <<: *api
    container_name: api-2
    hostname: api-2
    environment:
      PAYMENT_SERVICE_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_SERVICE_URL_FALLBACK: http://payment-processor-fallback:8080
      WORKERS_COUNT: 6
      RELEASE_COOKIE: rinha
      RELEASE_NODE: api@api2
      RELEASE_DISTRIBUTION: sname
      SIBLING: api@api1

  lb:
    <<: *server
    depends_on:
      - api1
      - api2

networks:
  payment-processor:
    external: true
  rinha-backend-ex:
    driver: bridge
