x-service-templates:
  api: &api
    image: wellingtonbp/rinha_de_backend_ex:v2
    environment:
      DB_CONN_URL: ecto://rinha:rinha@rinha-db/db
      PAYMENT_SERVICE_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_SERVICE_URL_FALLBACK: http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.56'
          memory: '127MB'

  db: &db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.28'
          memory: '86MB'

  server: &server
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-backend-ex
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10MB'

services:
  db:
    <<: *db
    container_name: rinha-db
    hostname: rinha-db

  api1:
    <<: *api
    container_name: api-1
    hostname: api-1
    depends_on:
      - db

  api2:
    <<: *api
    container_name: api-2
    hostname: api-2
    depends_on:
      - db

  lb:
    <<: *server
    depends_on:
      - api1
      - api2

networks:
  payment-processor:
    external: true
  rinha-backend-ex:
    driver: bridge
