services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  api01:
    image: ghcr.io/gabriell915/api-rinha-backend-hono-2025:latest
    environment:
      REDIS_URI: "redis://redis:6379"
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "65MB"
  api02:
    image: ghcr.io/gabriell915/api-rinha-backend-hono-2025:latest
    environment:
      REDIS_URI: "redis://redis:6379"
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "65MB"
  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: >-
      redis-server
      --save ""
       --appendonly no
      --maxclients 1024
      --maxmemory 50mb
      --timeout 30
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true