version: '3.8'

services:
  rinha-redis:
    image: redis:8.0.3-alpine
    container_name: rinha-v1-redis
    restart: always
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxclients 15000
      --tcp-keepalive 60
      --timeout 300
    networks:
      - rinha-network
      - payment-processor
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  rinha-v1-api:
    image: cicerocg/rinha-v1:latest
    platform: linux/amd64
    container_name: rinha-v1-api
    ports:
      - "9999:8080"
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      rinha-redis:
        condition: service_healthy
    environment:
      - REDIS_URL=rinha-redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - GOMAXPROCS=2
      - GOGC=200
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "280MB"
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5

networks:
  rinha-network:
    driver: bridge
    name: rinha-v1-network
  payment-processor:
    external: true
    name: payment-processor