x-service-templates:
  payment-service: &payment-service
    image: tiagodolphine/payment-service-go:0.0.2
    #pull_policy: always
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - REDIS_MAX_POOL_SIZE=120
      - POLL_INTERVAL=50
      - WORKERS=30
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: "110MB"
    depends_on:
      redis:
        condition: service_healthy

services:
  payment-service-1:
    <<: *payment-service
    container_name: payment-service-1

  payment-service-2:
    <<: *payment-service
    container_name: payment-service-2

  redis:
    image: redis:8.2.0-alpine3.22
    container_name: redis
    command: [ "redis-server","--save", "" , "--appendonly", "no", "--maxmemory", "60mb", "--maxmemory-policy", "allkeys-lru","--loglevel", "notice" ]
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: "75MB"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 10

#  haproxy:
#    image: haproxy
#    container_name: haproxy-lb
#    volumes:
#      - ./haproxy:/usr/local/etc/haproxy:ro
#    ports:
#      - "9999:9999"
#    depends_on:
#      - payment-service-1
#      - payment-service-2
#    deploy:
#      resources:
#        limits:
#          cpus: '0.3'
#          memory: "60MB"
#    networks:
#      - backend

  nginx:
    image: nginx:1.29-alpine3.22
    container_name: nginx-lb
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-service-1
      - payment-service-2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: "55MB"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true