x-enviromments: &x-enviromments
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/?tcp_nodelay=true"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "1"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"
version: '3.4'
services:
  app1: &app
    image: docker.io/lukas8219/rinha-de-backend-2025-app:main-5538a05e7-1753756591
    user: "1001:1001"
    hostname: app1
    restart: unless-stopped
    ipc: host
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app1.sock"
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '40MB'
  app2:
    <<: *app
    user: "1001:1001"
    ipc: host
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app2.sock"
    hostname: app2
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started
  consumer: &consumer
    <<: *app
    user: "1001:1001"
    hostname: "1"
    ipc: host
    cpuset: "0"
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/1.sock"
    cpu_shares: 3072
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '150MB'
        reservations:
          cpus: '0.9'
          memory: '150MB'
      image: docker.io/lukas8219/rinha-de-backend-2025-worker:main-5538a05e7-1753756591
    depends_on:
      lavinmq:
        condition: service_healthy
  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ./lavinmq.ini:/etc/lavinmq/lavinmq.ini:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '35MB'
        reservations:
          cpus: '0.3'
          memory: '35MB'
  nginx:
    image: nginx:latest
    container_name: nginx
    user: "1001:1001"
    ipc: host
    depends_on:
      - app1
      - app2
      - lavinmq
      - consumer
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '55MB'
        reservations:
          cpus: '0.1'
          memory: '55MB'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
      - nginx_run:/var/run
      - nginx_log:/var/log/nginx
volumes:
  nginx_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0755"
  nginx_run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0755"
  nginx_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001,mode=0755"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
