services:
  api1: &api-service
    image: eber404/dudebank:0.0.4
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/api1.sock
    networks:
      - backend
      - payment-processor
    volumes:
      - socket_data:/tmp
    depends_on:
      - memorydb
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '120MB'

  api2:
    <<: *api-service
    environment:
      - SERVER_SOCKET_PATH=/tmp/api2.sock

  memorydb:
    image: eber404/dudebank-db:0.0.4
    volumes:
      - socket_data:/tmp
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '90MB'

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  memorydb_data:
