services:
  api-1: &api-service
    image: eber404/dudebank:0.0.8
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/api_1.sock
    networks:
      - backend
      - payment-processor
    volumes:
      - socket_data:/tmp
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.675'
          memory: '135MB'

  api-2:
    <<: *api-service
    environment:
      - SERVER_SOCKET_PATH=/tmp/api_2.sock

  database:
    image: eber404/dudebank-db:0.0.8
    volumes:
      - socket_data:/tmp
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '15MB'

  load-balancer:
    image: eber404/dudebank-balancer:0.0.1
    volumes:
      - socket_data:/tmp
    networks:
      - backend
    ports:
      - '9999:80'
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '65MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  socket_data:
