services:
  api_0: &api
    image: ghcr.io/lothyriel/rinha_2025:v0.1.1
    volumes:
      - uds:/var/run
    command: ["-m", "api"]
    depends_on:
      - worker
    environment:
      NGINX_SOCKET: "/var/run/api_0.sock"
      RUST_LOG: "warn"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  api_1:
    <<: *api
    environment:
      NGINX_SOCKET: "/var/run/api_1.sock"
      RUST_LOG: "warn"

  worker:
    image: ghcr.io/lothyriel/rinha_2025:v0.1.1
    networks:
      - payment-processor
    volumes:
      - uds:/var/run
    command: ["-m", "worker"]
    environment:
      RUST_LOG: "warn"
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - uds:/var/run
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

volumes:
  uds:

networks:
  payment-processor:
    external: true
