x-service-templates:
  payment-gateway: &payment-gateway
    image: docker.io/phaalonso/rinha-backend-2025-java:0.0.3
    hostname: api01
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    environment:
      JAVA_OPTS: >-
        -XX:+UseZGC
        -Djdk.tracePinnedThreads=full
      "pagamento.processor.concurrency": 1000
      "pagamento.processor.default.url": http://payment-processor-default:8080
      "pagamento.processor.fallback.url": http://payment-processor-fallback:8080
      "spring.datasource.url": jdbc:postgresql://db:5432/rinha
      "spring.datasource.username": postgres
      "spring.datasource.password": postgres
      "spring.datasource.hikari.minimum-idle": 25
      "spring.datasource.hikari.maximum-pool-size": 50
      "spring.datasource.hikari.idle-timeout": 5000
      "spring.datasource.hikari.connection-timeout": 1000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
services:
  api01:
    <<: *payment-gateway
    container_name: api01
    hostname: api01
    ports:
      - "8080:8080"
  api02:
    <<: *payment-gateway
    container_name: api02
    hostname: api02
    ports:
      - "8081:8080"
  db:
    container_name: db
    hostname: db
    image: postgres:17-alpine
    #command: postgres -c config-file=/etc/postgres.conf
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql:ro
      - ./postgres.conf:/etc/postgres.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "rinha", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
