x-service-templates:
  payment-gateway: &payment-gateway
    image: phaalonso/rinha-backend-2025-java:0.0.1
    hostname: api01
    networks:
      - payment-processor

services:
  api01:
    <<: *payment-gateway
    container_name: api01
    hostname: api01
    ports:
      - "8080:8080"
    environment:
      PAGAMENTOS_PROCESSOR_CONCURRENCY: 1000
      JAVA_OPTS: >-
        -XX:+UseZGC
    deploy:
      resources:
        limits:
          cpus: "1.3"
          memory: "300MB"

  #  api02:
  #    <<: *payment-gateway
  #    container_name: api02
  #    hostname: api02
  #    ports:
  #      - "8081:8080"

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
