x-build_template: &build
  image: niltonkummer/rinha-backend-go-haproxy-2025:1.0.0
  networks:
    - backend-network
    - payment-processor

services:
  api1: &api
    <<: *build
    command: [ "/bin/api", "api" ]
    hostname: api1
    environment:
      - SOCKET_PATH=/unix-sock/api1.sock
    depends_on:
      - cache
    volumes:
      - unix-sock:/unix-sock:rw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "36MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - SOCKET_PATH=/unix-sock/api2.sock

  api3:
    <<: *api
    hostname: api3
    environment:
      - SOCKET_PATH=/unix-sock/api3.sock
 # 108 RAM
  consumer1:
    <<: *build
    command: [ "/bin/api", "consumer" ]
    hostname: consumer1
    volumes:
      - unix-sock:/unix-sock:rw
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "40MB"

  cache:
    <<: *build
    command: [ "/bin/api", "cache" ]
    hostname: cache
    volumes:
      - unix-sock:/unix-sock:rw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "152MB"
# 148 + 152 = 300
  haproxy:
    image: haproxy:2.9
    networks:
      - backend-network
    depends_on:
      - api1
      - api2
      - api3
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - unix-sock:/unix-sock:rw
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 50M

volumes:
  unix-sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  backend-network:
    driver: bridge
  payment-processor:
    external: true
