services:
  api1: &api-service
    image: eber404/dudebank:latest
    env_file:
      - .env
    environment:
      - IS_MAIN_INSTANCE=true
    ports:
      - "3001:8080"
    networks:
      - backend
      - payment-processor
    volumes:
      - memorydb_data:/app/data
    depends_on:
      - memorydb
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"

  api2:
    <<: *api-service
    ports:
      - "3002:8080"

  memorydb:
    image: eber404/dudebank-db:latest
    volumes:
      - memorydb_data:/app/data
    networks:
      - backend
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  memorydb_data: