services:
  load-balance:
    image: lpj145/rinha-lb:1.04
    networks:
      - backend
      - payment-processor
    ports:
      - 9999:9999
    volumes:
    - ./dev/shm:/var/run/sockets
    environment:
      - SOCKET_DIR=/var/run/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "20MB"

  api1: &api
    image: lpj145/rinha-lb:1.04
    hostname: api1
    environment:
      - SOCKET_DIR=/var/run/sockets
      - MODE=worker
    volumes:
      - ./dev/shm:/var/run/sockets
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "150MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - MODE=worker
      - SOCKET_DIR=/var/run/sockets
      - HOST=api2
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
