services:
  load-balance:
    image: lpj145/rinha-lb:1.11
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    ports:
      - 9999:9999
    volumes:
    - ./dev/shm:/var/run/sockets
    environment:
      - SOCKET_DIR=/var/run/sockets
      - APPLY_SYSCTL=0
      - LB_THREADS=4
    depends_on:
      - api1
      - api2
    cpuset: "0,1"
    cpus: "1.5"
    mem_limit: "45MB"
    sysctls:
      net.core.somaxconn: "65535"
      net.ipv4.tcp_fastopen: "3"
      net.ipv4.tcp_max_syn_backlog: "16384"

  api1: &api
    image: lpj145/rinha-lb:1.11
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    hostname: api1
    environment:
      - SOCKET_DIR=/var/run/sockets
      - MODE=worker
    volumes:
      - ./dev/shm:/var/run/sockets
    networks:
      - backend
      - payment-processor
    cpus: "0.10"
    mem_limit: "150MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - MODE=worker
      - SOCKET_DIR=/var/run/sockets
      - HOST=api2
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
