x-service-templates:
  base: &base
    image: josiney/rdb25_02-amd64:69d188da
    networks:
      - backend
      - payment-processor

services:
  api1:
    <<: *base
    container_name: api1
    hostname: api1
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - PORT=9997
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: ./api
    depends_on:
      - worker1

  api2:
    <<: *base
    container_name: api2
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    environment:
      - PORT=9998
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: ./api
    depends_on:
      - worker1

  worker1:
    <<: *base
    container_name: worker1
    hostname: worker1
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "150MB"
    ports:
      - "9996:9996"
      - "9995:9995"
    environment:
      - PAYMENTS_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENTS_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
      - HEALTH_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments/service-health
      - HEALTH_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments/service-health
    command: ./worker

  lb:
    image: haproxy:latest
    container_name: haproxy_lb
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true