x-component: &component
  image: jonhkr/rb2025:9ccff3d
  # build:
  #   context: ./
  volumes:
    - sockets:/sockets:rw
x-api: &api
  <<: *component
  command: /api
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.40"
        memory: "54MB"
services:
  api1:
    <<: *api
    hostname: api1
    environment:
      - GOMAXPROCS=1
      - SOCKET_PATH=/sockets/api1.sock
      - WORKERS=20
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
  api2:
    <<: *api
    hostname: api2
    environment:
      - GOMAXPROCS=1
      - SOCKET_PATH=/sockets/api2.sock
      - WORKERS=20
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  db:
    <<: *component
    command: /db
    environment:
      - GOMAXPROCS=1
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "79MB"
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets:rw
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "35MB"

volumes:
  sockets:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true