services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    image: jonhkr/rb2025:2f7b9a8
    hostname: api1
    environment:
      - MASTER_NODE=true
      - DATABASE_URL=postgres://r2025:passwd@db:5432/r2025?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "128MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - MASTER_NODE=false
      - DATABASE_URL=postgres://r2025:passwd@db:5432/r2025?sslmode=disable
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    hostname: db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "79MB"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U r2025 -d r2025" ]
      interval: 1s
      retries: 10
      start_period: 2s
      timeout: 10s
    environment:
      POSTGRES_USER: r2025
      POSTGRES_PASSWORD: passwd

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
