services:
  api1: &api
    image: lhuizf/rinha-de-backend-2025-bun:0.3.1
    hostname: api1
    container_name: api1
    environment:
      - PORT=3333
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: ["bun", "run", "src/index.ts"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

  api2:
    <<: *api
    hostname: api2
    container_name: api2

  worker1: &worker
    image: lhuizf/rinha-de-backend-2025-bun:0.3.1
    hostname: worker1
    container_name: worker1
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - DATABASE_PORT=5432
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - QUEUE_CONCURRENCY=20
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
      api1:
        condition: service_healthy
      db:
        condition: service_healthy
    command: ["bun", "run", "src/worker.ts"]
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "85MB"

  worker2:
    <<: *worker
    hostname: worker2
    container_name: worker2
    depends_on:
      redis:
        condition: service_healthy
      api2:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "20000",
        "--tcp-backlog",
        "511",
        "--dynamic-hz",
        "yes",
      ]
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"

  db:
    image: postgres:17-alpine
    container_name: db
    hostname: db
    environment:
      - POSTGRES_DB=rinha_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    # ports:
    #   - "5432:5432"
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

  load-balancer:
    image: nginx:1.25.2-alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true
